### PR TITLE
Changed currency names to country names

### PR DESCRIPTION
**Pull request by rrhythmsharma**
@MarkFChavez please review changes

currency- to-country

Solve this #3 issue

### CODE REVIEW

**Comment by MarkFChavez** [comment]
Thanks!

**Comment by MarkFChavez** [comment]
Btw, you should be able to see the changes already on https://bitcoinpriceindex.netlify.com

**Comment by rrhythmsharma** [comment]
that's awesome! :+1:

**Comment by rrhythmsharma** [comment]
I've also noticed we are using baseUrl directly in fetch function [here](https://github.com/MarkFChavez/bitcoin-price-index/blob/master/src/App.js#L28). I think as a good programming practice we should use a variable there.

something like this
```
state =  {   
    baseUrl: 'https://api.coindesk.com/v1/bpi/historical/close.json',
    currencyFilter: '?currency='
}
fetch(baseUrl + currencyFilter + ${this.state.currency})
```

**Comment by MarkFChavez** [comment]
Sure. Feel free to make the change. What do you think about extracting only the `baseUrl` and leave the other variables as is? Something like:

```
const baseUrl = ``
fetch(`${baseUrl}?currency=${currency}`)
```

**Comment by rrhythmsharma** [comment]
Agree, working on it :)

**Pull request merged**
